#!/bin/sh
BASEDIR="$(dirname $0)/../.."

if git diff-index --quiet HEAD --; then

echo "1"

cd $BASEDIR && make test
RESULT=$?

else

git stash -q --keep-index -u
cd $BASEDIR && make test
RESULT=$?
git stash pop -q

echo "2"

fi

[ $RESULT -ne 0 ] && exit 1
exit 0
